In [ ]:
import numpy as np

### **Array vs Lista**

> *Las **`listas`** son estructuras flexibles de alto nivel; los **`arrays`** de NumPy son estructuras homogéneas optimizadas para cómputo numérico y base del stack analítico.*

| Característica | Listas (Python Nativo) | Arrays (NumPy) |
| :--- | :--- | :--- |
| **Tipo de Datos** | **Heterogéneas:** Pueden guardar `int`, `str` y `bool` en la misma lista. | **Homogéneas:** Todos los elementos deben ser del mismo tipo (ej. solo `float64`). |
| **Rendimiento** | **Lento:** Requiere iterar con bucles `for` para operaciones matemáticas. | **Extremadamente Rápido:** Utiliza vectorización escrita en C y Fortran. |
| **Consumo de Memoria** | **Alto:** Almacena punteros a objetos dispersos en la memoria. | **Bajo:** Almacena los datos de forma contigua en bloques de memoria. |
| **Operaciones** | No soportan operaciones matemáticas directas (ej. `lista * 2` duplica la lista). | Soportan operaciones elemento a elemento (ej. `array * 2` multiplica cada número). |
| **Flexibilidad** | **Muy alta:** Fácil de redimensionar, añadir o quitar elementos. | **Menor:** Tienen un tamaño fijo al crearse; cambiar el tamaño requiere crear uno nuevo. |



In [ ]:
lista = [1, 2, 3]
arr = np.array([1,2,3])

print(f"""
lista -> {lista} -> {type(lista).__name__}
Array(np) -> {arr} -> {type(arr).__name__}
""")


lista -> [1, 2, 3] -> list
Array(np) -> [1 2 3] -> ndarray



---
### **`np.arange(n)`**
  
Se obtiene un array a partir del rango indicado (n)

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---
**Arrays con tipo de datos específicos**

In [ ]:
# enteros
arr_int = np.array([1, 2, 3], dtype="int32")

# flotante
arr_float = np.array([1, 2, 3], dtype="float32")

print(arr_int)
print(arr_float)

[1 2 3]
[1. 2. 3.]
