In [2]:
import numpy as np

---

### **Selección de elementos**
  
**Indexing**

In [3]:
arr = np.arange(10)
print(f"arr = {arr}")
print(f"elemento 2 -> {arr[1]}")

arr = np.array([[4, 2, 1], [6, 9, 3], [10, 11, 15]])
print(f"arr = {arr}")
print(f"elemento fila 2 columa 3 -> {arr[1, 2]}")

arr = [0 1 2 3 4 5 6 7 8 9]
elemento 2 -> 1
arr = [[ 4  2  1]
 [ 6  9  3]
 [10 11 15]]
elemento fila 2 columa 3 -> 3


---

**Slicing**

In [4]:
arr = np.arange(10)
print(f"arr = {arr}")
print("Slicing arr[2:7] ->\n", arr[2:7])

# arr[raw, col]
arr = np.array([[4, 5, 6, 2, 1, 56, 22], [0, 1, 6, 9, 12, 11, 3], [7, 12, 67, 2, 10, 11, 15]])
print(f"\narr = \n{arr}")
print("\nlicing arr[:2, :2] ->\n",arr[:2, :2])

# Seleccionar todas las filas (:) y, de las columnas, toma cada tercera columna empezando desde la primera (::3)
print("\nSeleccionar todas las filas (:) y, de las columnas, toma cada 2da columna empezando desde la primera (::2)\nSlicing arr[:, ::2] ->\n",arr[:, ::2])

arr = [0 1 2 3 4 5 6 7 8 9]
Slicing arr[2:7] ->
 [2 3 4 5 6]

arr = 
[[ 4  5  6  2  1 56 22]
 [ 0  1  6  9 12 11  3]
 [ 7 12 67  2 10 11 15]]

licing arr[:2, :2] ->
 [[4 5]
 [0 1]]

Seleccionar todas las filas (:) y, de las columnas, toma cada 2da columna empezando desde la primera (::2)
Slicing arr[:, ::2] ->
 [[ 4  6  1 22]
 [ 0  6 12  3]
 [ 7 67 10 15]]


**Indexación avanzada**

In [5]:
arr = np.arange(10)
print(f"arr = {arr}")

index = np.array([1, 4, -1])
print(f"\nindex = {index}")

print("\nObenemos elementos de la posición 1, 4 y último (-1)\narr[index] ->\n", arr[index])

arr = [0 1 2 3 4 5 6 7 8 9]

index = [ 1  4 -1]

Obenemos elementos de la posición 1, 4 y último (-1)
arr[index] ->
 [1 4 9]


**Indexación Booleana**

In [6]:
arr = np.array([9, 7, 30, 67, 15])
print("arr\n->", arr)

# multiplos de 3
condition = (arr % 3) == 0

print("\nmultiplos de 3\n->", condition)

# Solo obtendré un array con los valores true

print("\narr[condition]\n->", arr[condition])

arr
-> [ 9  7 30 67 15]

multiplos de 3
-> [ True False  True False  True]

arr[condition]
-> [ 9 30 15]
