In [1]:
import numpy as np

# **Broadcasting**

El **Broadcasting** es, posiblemente, el concepto más importante para entender por qué NumPy es tan eficiente. Es el conjunto de reglas que permite a NumPy realizar operaciones aritméticas entre arrays con diferentes formas (*shapes*) como si tuvieran las mismas dimensiones, sin necesidad de duplicar datos innecesariamente en la memoria.

---

## 🛠️ ¿Qué es el Broadcasting?

En Python puro, si quisieras sumar un número a cada elemento de una lista, necesitarías un bucle `for`. En NumPy, gracias al broadcasting, puedes simplemente hacer `array + 5`. NumPy "transmite" (o estira virtualmente) el valor más pequeño para que coincida con el más grande.

> **Importante:** El broadcasting no crea copias reales de los datos en la memoria, lo que lo hace extremadamente eficiente.

---

## 📏 Las 2 Reglas de Oro

Para que dos arrays sean compatibles para broadcasting, NumPy compara sus dimensiones **empezando desde la derecha** (las dimensiones finales). Dos dimensiones son compatibles cuando:

1. **Son iguales.**
2. **Una de ellas es 1.**

### El proceso de decisión:

1. Si los arrays tienen un número diferente de dimensiones, se añaden dimensiones de tamaño **1** a la izquierda del array más pequeño hasta que coincidan.
2. Si en alguna dimensión los tamaños no coinciden y ninguno es **1**, NumPy lanzará un `ValueError`.

---

## 📊 Ejemplos de Compatibilidad

Imagina que tienes los siguientes arrays con sus respectivos *shapes*:

| Array A | Array B | ¿Es compatible? | Explicación |
| --- | --- | --- | --- |
| (3, 3) | (3, 3) | **Sí** | Dimensiones iguales. |
| (3, 3) | (3,) | **Sí** | B se trata como . El 1 se estira. |
| (8, 1, 6, 1) | (7, 1, 5) | **Sí** | Se compara de derecha a izquierda; los 1 se estiran. |
| (3, 2) | (3, 3) | **No** | Las dimensiones finales (2 y 3) no coinciden ni son 1. |

## Explicación

### 1. Caso Complejo: `(8, 1, 6, 1)` vs `(7, 1, 5)`

Este es el ejemplo clásico de "estiramiento" múltiple. Sigamos los pasos que realizaría internamente NumPy:

**Paso A: Alineación y Relleno (Padding)**
NumPy ve que el Array B tiene menos dimensiones. Entonces, rellena con  a la izquierda para que ambos tengan la misma cantidad de "columnas de dimensiones".

* **Array A:** (8, 1, 6, 1)
* **Array B:** (7, 1, 5) <- *(Agregamos un 1 al principio)*

**Paso B: Comparación de derecha a izquierda**
Ahora comparamos pareja por pareja:

1. **Dimensión 4 (Final): *A=1* y *B=5*. **Compatible**. El 1 de *A* se "estira" para igualar al 5.
2. **Dimensión 3: *A=6* y *B=1*. **Compatible**. El 1 de *B* se "estira" para igualar al 6.
3. **Dimensión 2: *A=1* y *B=7*. **Compatible**. El 1 de *A* se "estira" para igualar al 7.
4. **Dimensión 1 (Inicial): *A=8* y *B=1*. **Compatible**. El 1 de *B* se "estira" para igualar al 8.

**Resultado final:** La operación es un éxito y el array resultante tendrá un shape de (8, 1, 6, 1).

---

### 2. Caso de Error: `(3, 2)` vs `(3, 3)`

Este ejemplo es el "estafador", porque a simple vista parece que deberían encajar (ambos tienen un ), pero las reglas de NumPy son estrictas con el orden.

**Paso A: Alineación**
Ambos tienen 2 dimensiones, así que no hay nada que rellenar.

* **Array A:** (3, 2)
* **Array B:** (3, 3)

**Paso B: Comparación de derecha a izquierda**

1. **Dimensión 2 (Final): *A=2* y *B=3*. **INCOMPATIBLE**.
* ¿Son iguales? **No**.
* ¿Alguno de los dos es 1? **No**.



**Resultado:** Aquí es donde NumPy se detiene y lanza el famoso `ValueError: operands could not be broadcast together`. No importa que la siguiente dimensión sea un  en ambos; si la última dimensión no encaja, el proceso se rompe inmediatamente.

---

## 💻 Ejemplo Práctico en Código

Aquí verás cómo NumPy aplica estas reglas automáticamente para normalizar datos, algo muy común en un analista.

```python
import numpy as np

# Matriz de 3x3 (ej: 3 alumnos, 3 exámenes)
notas = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])

# Vector de 1x3 (ej: puntos extra para cada examen)
puntos_extra = np.array([1, 2, 3])

# Resultado: Los puntos extra se suman a cada fila automáticamente
resultado = notas + puntos_extra

print(resultado)
# [[11, 22, 33],
#  [41, 52, 63],
#  [71, 82, 93]]

```

---

## 💡 Tips 
* **Verifica el shape:** Siempre que tengas dudas de por qué un cálculo falla, imprime `arr.shape`.
* **Añadir dimensiones manuales:** Si necesitas forzar el broadcasting, puedes usar `np.newaxis` para convertir un vector fila en un vector columna.
* **Memoria:** Recuerda que el broadcasting es "perezoso". Solo calcula lo que necesita, lo cual es vital cuando trabajes con datasets grandes en **AWS** o **Databricks**.
* El broadcasting es lo que permite que herramientas como **Spark** (en Databricks) o **Redshift** (en AWS) operen de forma distribuida de manera eficiente.

---

### **Operaciones básicas**

**Arrays y Escalar**

In [2]:
A = np.array([8, 22, 64])


print(f"A -> {A}")

# RESTA
C = A-2
print("\nA - 2 ->", C)

# SUMA 
C = A+2
print("\nA + 2 ->", C)

# Multiplicación 
C = A*2
print("\nA * 2 ->", C)

# Dovisión
C = A/2
print("\nA / 2 ->", C)



A -> [ 8 22 64]

A - 2 -> [ 6 20 62]

A + 2 -> [10 24 66]

A * 2 -> [ 16  44 128]

A / 2 -> [ 4. 11. 32.]


**Arrays**

In [3]:
A = np.array([4, 6, 8])
B = np.array([2, 2, 2])

print(f"A -> {A}\nB -> {B}")

# RESTA
C = A-B
print("\nA - B ->", C)

# SUMA 
C = A+B
print("\nA + B ->", C)

# Multiplicación 
C = A*B
print("\nA * B ->", C)

# Dovisión
C = A/B
print("\nA / B ->", C)

A -> [4 6 8]
B -> [2 2 2]

A - B -> [2 4 6]

A + B -> [ 6  8 10]

A * B -> [ 8 12 16]

A / B -> [2. 3. 4.]


In [4]:
A = np.array([[4, 6, 8], [7, 1, 5], [6, 8, 1]])
B = np.array([[2, 2, 2], [9, 12, 64], [12, 6, 4]])
D = np.array([[2], [9], [12]])

print(f"A\n{A}\nB\n{B}")

# RESTA
C = A-B
print("\nA - B ->\n", C)

# SUMA 
C = A+B
print("\nA + B ->\n", C)

# Multiplicación 
C = A*B
print("\nA * B ->\n", C)

# Dovisión
C = A/B
print("\nA / B ->\n", C)

A
[[4 6 8]
 [7 1 5]
 [6 8 1]]
B
[[ 2  2  2]
 [ 9 12 64]
 [12  6  4]]

A - B ->
 [[  2   4   6]
 [ -2 -11 -59]
 [ -6   2  -3]]

A + B ->
 [[ 6  8 10]
 [16 13 69]
 [18 14  5]]

A * B ->
 [[  8  12  16]
 [ 63  12 320]
 [ 72  48   4]]

A / B ->
 [[2.         3.         4.        ]
 [0.77777778 0.08333333 0.078125  ]
 [0.5        1.33333333 0.25      ]]


In [5]:
A = np.array([[4, 6, 8], [7, 1, 5], [6, 8, 1]])
D = np.array([[2], [9], [12]])

print(f"A\n{A}\nD\n{D}")

C = A*D
print("\nA * D ->\n", C)


A
[[4 6 8]
 [7 1 5]
 [6 8 1]]
D
[[ 2]
 [ 9]
 [12]]

A * D ->
 [[ 8 12 16]
 [63  9 45]
 [72 96 12]]
