In [3]:
import numpy as np

In [ ]:
# copia directa y mutable
A = np.array([3, 12, 512])
B = A

A[2] = 21

In [6]:
print(f"A: {A}")
print(f"B: {B}")

A: [ 3 12 20]
B: [ 3 12 20]


In [ ]:
# copia limpia, pero consume memoria (a tener en cuenta)
A = np.array([6, 18, 30])
B = A.copy()

A[2] = 36

In [8]:
print(f"A: {A}")
print(f"B: {B}")

A: [ 6 18 36]
B: [ 6 18 30]


### Tranformar arrays con `.reshape()`

In [10]:
A = np.arange(1, 10)
print("A:\n", A)

A = A.reshape(3,3)
print("A:\n", A)

A:
 [1 2 3 4 5 6 7 8 9]
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Aplanar con `flatten()` o `ravel()` 

In [ ]:
# Crea un copia independiente
print("A:\n", A.flatten())

# Apunta al mismop espacio de memoria del arrays a transformar
print("A:\n", A.ravel())

A:
 [1 2 3 4 5 6 7 8 9]
A:
 [1 2 3 4 5 6 7 8 9]
